### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by SidTheEngineer** [masoncadams/tea-cozy#4]
**Overall:** Meets expectations

Your code looks great, it is indented well and there are no issues in your CSS. The site is just about spot on and looks great as well.

**Areas for improvement:**

There are no glaring flaws with the site, you've done really well 👍 . There are a couple of minor things to adjust that were mentioned in a couple of previous issues, such as some adjustments to the look and feel of the nav bar, as well as some minor padding changes to the mission portion of the site. With these minor improvements, the project will be perfect.

**Comment by masoncadams** [comment]
Thanks!
